name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Uname
        run: uname -a

      - name: Compile
        run: clang -Wall -Wextra main.c

      - name: Run
        run: ./a.out
